"""
Deterministic friendly-label generator for VM DNS names.

Given a numeric VM ID, returns a stable ``adjective-noun`` label such as
``brave-falcon``.  The same ID always produces the same label; different IDs
produce different labels across the entire cross-product of the two lists.

No external dependencies — uses only the standard library.
"""

from __future__ import annotations

import hashlib
import random as _random

_ADJECTIVES: list[str] = [
    "agile",
    "amber",
    "ancient",
    "arctic",
    "azure",
    "bold",
    "brave",
    "breezy",
    "bright",
    "calm",
    "cedar",
    "clear",
    "cloudy",
    "coastal",
    "cool",
    "crisp",
    "cyber",
    "daring",
    "dark",
    "deep",
    "distant",
    "dusk",
    "dynamic",
    "eager",
    "earthy",
    "electric",
    "elegant",
    "emerald",
    "endless",
    "epic",
    "eternal",
    "exotic",
    "faint",
    "fast",
    "feral",
    "fierce",
    "fine",
    "firm",
    "fleet",
    "flowing",
    "free",
    "fresh",
    "frozen",
    "gentle",
    "glowing",
    "golden",
    "graceful",
    "grand",
    "great",
    "green",
    "happy",
    "harsh",
    "heavy",
    "high",
    "hollow",
    "hot",
    "humble",
    "icy",
    "inner",
    "iron",
    "ivory",
    "jade",
    "jagged",
    "keen",
    "kind",
    "large",
    "lazy",
    "lean",
    "light",
    "lively",
    "lofty",
    "long",
    "lost",
    "loud",
    "loyal",
    "lucky",
    "lunar",
    "magic",
    "mellow",
    "mighty",
    "mild",
    "misty",
    "modern",
    "moving",
    "narrow",
    "natural",
    "neutral",
    "nimble",
    "noble",
    "open",
    "orange",
    "outer",
    "pale",
    "peaceful",
    "plain",
    "polar",
    "prime",
    "proud",
    "pure",
    "quick",
    "quiet",
    "radiant",
    "rapid",
    "roaming",
    "round",
    "royal",
    "rustic",
    "sharp",
    "silent",
    "silver",
    "sleek",
    "smart",
    "solar",
    "solid",
    "stark",
    "stellar",
    "still",
    "stone",
    "swift",
    "tall",
    "teal",
    "vivid",
    "warm",
    "wild",
    "wise",
    "zesty",
]

_NOUNS: list[str] = [
    "abyss",
    "anchor",
    "arch",
    "arrow",
    "ash",
    "atlas",
    "aurora",
    "basin",
    "bay",
    "beacon",
    "beam",
    "blade",
    "bloom",
    "bolt",
    "breeze",
    "bridge",
    "brook",
    "byte",
    "canyon",
    "cloud",
    "comet",
    "coral",
    "crane",
    "crest",
    "crystal",
    "dawn",
    "delta",
    "dome",
    "drift",
    "dune",
    "eagle",
    "echo",
    "falcon",
    "fern",
    "field",
    "fjord",
    "flame",
    "flare",
    "flash",
    "flux",
    "forge",
    "frost",
    "gale",
    "gem",
    "glen",
    "glow",
    "grove",
    "gulf",
    "hawk",
    "haven",
    "haze",
    "helm",
    "hill",
    "hive",
    "horizon",
    "iris",
    "isle",
    "jet",
    "kelp",
    "kestrel",
    "knoll",
    "lake",
    "lance",
    "lark",
    "lava",
    "leaf",
    "lens",
    "light",
    "lion",
    "lotus",
    "lynx",
    "maple",
    "marsh",
    "maze",
    "mesa",
    "mist",
    "moon",
    "moss",
    "needle",
    "nest",
    "node",
    "nova",
    "oak",
    "opal",
    "orbit",
    "path",
    "peak",
    "pine",
    "pixel",
    "pool",
    "port",
    "prism",
    "pulse",
    "quartz",
    "raven",
    "reef",
    "ridge",
    "river",
    "rock",
    "root",
    "rover",
    "sage",
    "sand",
    "seal",
    "shell",
    "shore",
    "slate",
    "slope",
    "snow",
    "spark",
    "spine",
    "spire",
    "star",
    "stone",
    "stream",
    "summit",
    "surf",
    "swan",
    "terra",
    "thorn",
    "tide",
    "tower",
    "trail",
    "vault",
    "vale",
    "wave",
    "wind",
    "zone",
]

# Total combinations: 126 × 128 = 16 128
# Covers all vm_ids in [0, 16 128) with zero collision.
# New VMs start at 5001 → supports ~11 000 new VMs before wrapping.
_N: int = len(_ADJECTIVES) * len(_NOUNS)

# Build a stable, seeded permutation of [0, _N) once at import time.
# Fisher-Yates with a fixed key → bijection → zero collisions guaranteed.
_seed = int(hashlib.sha256(b"minet-hosting-dns-perm-v1").hexdigest(), 16) & ((1 << 64) - 1)
_perm: list[int] = list(range(_N))
_random.Random(_seed).shuffle(_perm)
del _seed


def vm_dns_label(vm_id: int) -> str:
    """Return a stable, human-friendly DNS label for the given VM ID.

    Uses a seeded Fisher-Yates permutation so that:
    - The same ID always produces the same label.
    - Every ID in ``[0, 16 128)`` produces a **unique** label (zero collisions).
    - Labels are not trivially enumerable from sequential IDs.

    :param vm_id: Numeric VM identifier.
    :returns: A DNS-safe label of the form ``adjective-noun``.
    :rtype: str
    """
    idx = _perm[vm_id % _N]
    adj = _ADJECTIVES[idx % len(_ADJECTIVES)]
    noun = _NOUNS[idx // len(_ADJECTIVES)]
    return f"{adj}-{noun}"
