local-address=0.0.0.0,::
include-dir=/etc/powerdns/pdns.d

# Allow AXFR from any source (ingress mode rewrites source IPs)
allow-axfr-ips=0.0.0.0/0,::/0
# Notify ns1/ns2 on zone changes
also-notify=192.168.102.55,192.168.102.54
